service: TNS

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    API_KEY: ${env:API_KEY}
    DISCORD_WEBHOOK_URL: ${env:DISCORD_WEBHOOK_URL}

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi: "*"

  dailySummary:
    handler: dist/cron.handler
    events:
      - schedule:
          rate: cron(0 15 * * ? *)
          input: {}
    maximumRetryAttempts: 0

package:
  excludeDevDependencies: true
  patterns:
    - "!src/**"
    - "!data/**"
    - "!tests/**"
    - "!**/*.test.*"
    - "!**/*.spec.*"
    - "!**/*.log"
    - "!tsconfig.json"
    - "!serverless.yml"
    - "!.env"
